---
apiVersion: v1
kind: Service
metadata:
  name: {{.Values.app.name}}-tcp80
  namespace: {{.Values.app.namespace}}
  annotations:
    alb.ingress.kubernetes.io/healthcheck-interval-seconds: '300'
    #alb.ingress.kubernetes.io/target-type: ip
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  type: NodePort
  selector:
    app: {{.Values.app.name}}